#!/usr/bin/env python3
"""
Step 5 — turns master_seasons.csv (+ master_games.csv, once it has rows)
into supabase/heisman-ledger/seed.sql: plain INSERT ... ON CONFLICT
statements Matt pastes into the Supabase SQL Editor himself, per the
cloud-session rule that this project's real Supabase credentials never get
typed into a Claude Code web session. Re-run this any time the master CSVs
change — seed.sql is a generated artifact, not hand-edited.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

# This file lives at scripts/heisman_ledger/generate_seed_sql.py -- three
# parents up is the repo root. Anchoring --master/--out's defaults here,
# rather than to a plain relative "../../...", means they resolve correctly
# no matter what directory this script is invoked from -- a relative
# default silently resolves against the process's cwd, not the script's
# own location, and writes outside the repo when run from somewhere other
# than scripts/heisman_ledger.
REPO_ROOT = Path(__file__).resolve().parent.parent.parent


def sql_str(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def sql_num(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    return value


def sql_bool(value: str | bool | None) -> str:
    if value is None or value == "":
        return "false"
    if isinstance(value, bool):
        return "true" if value else "false"
    return "true" if str(value).strip().lower() in ("true", "1") else "false"


def generate_seasons_sql(seasons_csv: Path) -> list[str]:
    lines = [
        "-- Generated by scripts/heisman_ledger/generate_seed_sql.py — do not hand-edit.",
        "-- Re-run the generator after merge_dataset.py produces a new master_seasons.csv.",
        "",
    ]
    with seasons_csv.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            values = ", ".join(
                [
                    sql_num(row["year"]),
                    sql_str(row["head_coach"]),
                    sql_str(row["conference"]),
                    sql_str(row["final_record"]),
                    sql_str(row["final_ap_rank"]),
                    sql_str(row["national_title_claim"]),
                    sql_num(_approx_int(row["points_for"])[0]),
                    sql_bool(_approx_int(row["points_for"])[1]),
                    sql_num(_approx_int(row["points_against"])[0]),
                    sql_bool(_approx_int(row["points_against"])[1]),
                    sql_str(row["beat_texas"]),
                    sql_str(row["beat_osu"]),
                    sql_str(row["heisman_winner"]),
                    sql_str(row["notable_all_americans"]),
                    sql_num(row["data_tier"]),
                    sql_str(row["source_notes"]),
                    sql_num(row.get("offense_ppa")),
                    sql_num(row.get("defense_ppa")),
                    sql_num(row.get("offense_success_rate")),
                    sql_num(row.get("defense_success_rate")),
                    sql_num(row.get("sp_overall")),
                    sql_num(row.get("sp_offense")),
                    sql_num(row.get("sp_defense")),
                    sql_num(row.get("offense_total_yards")),
                    sql_num(row.get("offense_rushing_yards")),
                    sql_num(row.get("offense_passing_yards")),
                    sql_num(row.get("offense_turnovers")),
                ]
            )
            lines.append(
                "insert into heisman_ledger_seasons (year, head_coach, conference, "
                "final_record, final_ap_rank, national_title_claim, points_for, "
                "points_for_is_approximate, points_against, points_against_is_approximate, "
                "beat_texas, beat_osu, heisman_winner, notable_all_americans, data_tier, "
                "source_notes, offense_ppa, defense_ppa, offense_success_rate, "
                "defense_success_rate, sp_overall, sp_offense, sp_defense, "
                "offense_total_yards, offense_rushing_yards, offense_passing_yards, "
                f"offense_turnovers)\nvalues ({values})"
            )
            lines.append(
                "on conflict (year) do update set "
                + ", ".join(
                    f"{col} = excluded.{col}"
                    for col in (
                        "head_coach", "conference", "final_record", "final_ap_rank",
                        "national_title_claim", "points_for", "points_for_is_approximate",
                        "points_against", "points_against_is_approximate", "beat_texas",
                        "beat_osu", "heisman_winner", "notable_all_americans", "data_tier",
                        "source_notes", "offense_ppa", "defense_ppa", "offense_success_rate",
                        "defense_success_rate", "sp_overall", "sp_offense", "sp_defense",
                        "offense_total_yards", "offense_rushing_yards", "offense_passing_yards",
                        "offense_turnovers",
                    )
                )
                + ";\n"
            )
    return lines


def _approx_int(value: str) -> tuple[str, bool]:
    """A value like '414+' means an approximate/partial total — see csv_to_json.py."""
    if not value:
        return value, False
    if value.strip().endswith("+"):
        return value.strip()[:-1], True
    return value, False


def generate_games_sql(games_csv: Path) -> list[str]:
    if not games_csv.exists():
        return ["-- master_games.csv not generated yet (no rows to seed)."]
    lines = []
    with games_csv.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        return ["-- master_games.csv has no rows yet — run the Wikipedia bulk pull first."]
    for row in rows:
        values = ", ".join(
            [
                sql_num(row["year"]),
                sql_num(row["game_order"]),
                sql_str(row["date"]),
                sql_str(row["opponent"]),
                sql_str(row["site_text"]),
                sql_str(row["home_away_guess"] or "unknown"),
                sql_str(row["result"]),
                sql_num(row["team_score"]),
                sql_num(row["opp_score"]),
                sql_str(row["notes"]),
            ]
        )
        lines.append(
            "insert into heisman_ledger_games (year, game_order, date, opponent, site_text, "
            f"home_away_guess, result, team_score, opp_score, notes)\nvalues ({values})\n"
            "on conflict (year, game_order) do update set "
            "date = excluded.date, opponent = excluded.opponent, site_text = excluded.site_text, "
            "home_away_guess = excluded.home_away_guess, result = excluded.result, "
            "team_score = excluded.team_score, opp_score = excluded.opp_score, "
            "notes = excluded.notes;\n"
        )
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--master", type=Path, default=REPO_ROOT / "data/heisman-ledger/master")
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "supabase/heisman-ledger/seed.sql")
    args = parser.parse_args()

    lines = generate_seasons_sql(args.master / "master_seasons.csv")
    lines.append("\n-- Games (opponent lists, for SOS math) --\n")
    lines.extend(generate_games_sql(args.master / "master_games.csv"))

    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
